module.exports = {
  env: {
    REACT_APP_NETWORK_URL: process.env.REACT_APP_NETWORK_URL,
    REACT_APP_CHAIN_ID: process.env.REACT_APP_CHAIN_ID,
    REACT_APP_SERVICE_FEE_RECEIVER: process.env.REACT_APP_SERVICE_FEE_RECEIVER,
    REACT_APP_SERVICE_FEE: process.env.REACT_APP_SERVICE_FEE
  }
}
